# App
spring:
  application:
    name: proyectoAlgoritmos

# Automatizaci√≥n
automation:
  email: "${ACADEMIC_EMAIL:hernand.benavidesc@uqvirtual.edu.co}"
  password: "${MAIL_PASSWORD:y7yvqqQph3xztWY@}"
  search:
    query: "generative artificial intelligence"
  download:
    directory: "src/main/resources/downloads"
  portal:
    url: "https://library.uniquindio.edu.co/databases"
  max:
    pages: 3
  headless: true
  auto-run: false  # cambia a true si quieres que corra al iniciar
  chrome:
    forceDirect: true           # abre conexiones DIRECT, sin proxy del sistema
    persistentProfile: false    # usa perfil temporal para evitar cookies/redirecciones previas
  dendrogramas:
    output-dir: "src/main/resources/data/dendrogramas"

logging:
  level:
    root: INFO
    co.edu.uniquindio.proyectoAlgoritmos: INFO
  file:
    name: ./logs/application.log

server:
  port: 8080